fastlane_version "1.106.2"
default_platform :ios

platform :ios do
  desc "Release to Testflight"
  lane :testflight do
    unit_test
    increment_build_number
    commit_version_bump
  end

  desc "Runs both unit and UI tests"
  lane :test do
    unit_test
    ui_test
  end

  desc "Runs all unit tests"
  lane :unit_test do
    scan(device: "#{"iPad Pro (10.5-inch)"}", scheme: "Calcupad")
  end

  desc "Runs all UI tests"
  lane :ui_test do
    scan(device: "#{"iPad Pro (10.5-inch)"}", scheme: "CalcupadUITests")
  end
end
