fastlane_version "1.106.2"
default_platform :ios

platform :ios do
  desc "Release to Testflight"
  lane :deploy_appstore do
    test_increment_build
    increment_version_number(bump_type: "minor")
    commit_version_bump
    gym(scheme: "Calcupad")
  end

  lane :deploy_testflight do
    test_increment_build
    commit_version_bump
    gym(scheme: "Calcupad")
    pilot
  end

  desc "Tests and increments the build"
  lane :test_increment_build do
    unit_test
    increment_build_number
  end

  desc "Runs both unit and UI tests"
  lane :test do
    unit_test
    ui_test
  end

  desc "Runs all unit tests"
  lane :unit_test do
    scan(device: "#{"iPad Pro (10.5-inch)"}", scheme: "Calcupad")
  end

  desc "Runs all UI tests"
  lane :ui_test do
    scan(device: "#{"iPad Pro (10.5-inch)"}", scheme: "CalcupadUITests")
  end
end
